### ISSUE TITLE
Scroll bars too narrow

### ISSUE THREAD

**Issue by HorstBaerbel** [xbmc/skin.estouchy#2]
Nice skin, but the scroll bars are really narrow and hard to hit on small screens. I'm using the skin on a 5" 800x480 display. An option to adjust them would be nice too...

**Comment by ronie** [comment]
i'll look into it, i probably can make the scrollbars a bit wider.

**Comment by ronie** [comment]
https://github.com/xbmc/skin.estouchy/commit/fa571234e3afb8586faf0e1868a02fbea6f2e89e
