### ISSUE TITLE
Make element sizes adjustable or provide skin-wide zoom factor

### ISSUE THREAD

**Issue by HorstBaerbel** [xbmc/skin.estouchy#3]
For small screens (e.g. 5" 800x480) it would be good to be able to adjust the size of some elements, like the left side toolbar for video/audio/images/addons when you're e.g. in the video category. Maybe a simple general "skin zoom" factor for each skin would already suffice. The font size would need to be scaled too, or the font size could be a separate option.
The user has to live with cut-off texts etc. if he/she sets the zoom too high...

**Comment by ronie** [comment]
it's not easy (if possible at all) to implement a 'skin zoom factor'.

**Comment by HorstBaerbel** [comment]
I'm not sure why Kodi doesn't have this btw, but whatever. Shall I open issues for every problem individually? This skin is looking to be the most touch-friendly one atm. I would like use it, but below a certain resolution you can barley hit the buttons. 800x480 is pretty common for diy projects and older smartphones. Imo you could even go as low a 480x320 or at least 640x480 and have a usable system and I though this is what this skin is for.
How can I help to improve the skin in that regard?

**Comment by MartijnKaijser** [comment]
Kodi was never ever intended to be used on phones or small screens and i'm sure no one on the team really has the intention to do so. That's the reason there are simply no other touch skins available.
A tablet of 7" is really the minimum you should use.

**Comment by HorstBaerbel** [comment]
Imo there's no reason to. It's all about the skin / GUI anyway.
Is there any problem with making a fork and adding a 480p-version of the skin? Would you be willing to pull that?

**Comment by NedScott** [comment]
@HorstBaerbel There would be no problem at all. Even if it is not pulled into the main Estouchy skin, many people would be willing to help make it a new skin that could be submitted. There is even a "car PC" fork of the old touch skin that works wonderfully on 4 and 5 inch screens, so we know it is entirely possible. It might simply need to be a specific "small screen" skin, rather than one universal touch skin.

**Comment by HorstBaerbel** [comment]
(rant)Stuff that is not going into distributed versions does usually die really quickly, simply because it becomes incompatible. Look at the myriad of forked stuff. It solves your problem today, but the next upgrade will break it again... Fragmentation makes me cry. (/rant)
Finding a current, working touch skin for small screens that does not need a patched Kodi version (that CarPC-thing) is hard. Imo they basically all suck. This is the closest thing to "usable".
I'll fiddle around with it when I find time. I was reading about creating skins / addons anyway...
