### ISSUE TITLE
Add option to hide the mouse cursor

### ISSUE THREAD

**Issue by HorstBaerbel** [xbmc/skin.estouchy#4]
On touch screens you may not want to see the mouse cursor, but can not disable mouse / touch input to hide it, so an option to hide the cursor would be useful. This can be manually done by using a 1x1 transparent PNG as the cursor image in Pointer.xml.

**Comment by ronie** [comment]
touchscreen devices usually don't have a mouse attached.
in case you do... as long as you don't use your mouse, kodi will not show a cursor.

if you think the current behaviour is wrong, file a bug report against kodi,
it's not something we should work around in the skin.
